### ISSUE TITLE
updater.bat uses taken down youtube-dl RSS

### ISSUE THREAD

**Issue by AstralStorm** [shinchiro/mpv-packaging#11]
Due to certain "polite request" from RIAA youtube-dl was taken off github into DMCA repo, making the RSS feed dead.
This results in the following when using updater.bat:

Fetching RSS feed for youtube-dl
The remote server returned an error: (451) Unavailable for Legal Reasons.
Press any key to continue . . .

**Comment by shinchiro** [comment]
Oh yeah, I almost forgot about this issue. I'll think another solution about this later
