### ISSUE TITLE
can you explain the purpose of d3dcompiler_43

### ISSUE THREAD

**Issue by hooke007** [shinchiro/mpv-packaging#14]
I found its filename was just renamed from `d3dcompiler_47`. But 43 is used for d3d9 while 47 support d3d11.

**Comment by shinchiro** [comment]
Used when select `gpu-api=d3d11` in mpv. Usually it already exist on system32. Buf if not, the bundled will serve the purpose

**Comment by hooke007** [comment]
emmm. I still cannot understand why make its filename `47` to `43`, but I know it can be deleted in my device.
