### ISSUE TITLE
mpv-install doesn't escape paths properly

### ISSUE THREAD

**Issue by andrew-boyarshin** [shinchiro/mpv-packaging#15]
E.g. `HKEY_CLASSES_ROOT\io.mpv.m4a\shell\open\command`: `"C:\ProgramData\Export\mpv.exe"  -- "%L`, the path argument is missing the end quote. Doesn't cause issues that I know of, but might still be worth a fix.

**Comment by shinchiro** [comment]
It might go unnoticed before. Could you create pr for it?
