### ISSUE TITLE
[request] please add docs for the tools at "installer"

### ISSUE THREAD

**Issue by avih** [shinchiro/mpv-packaging#16]
I think it would be useful to have some documentation for the tools at the `installer/` dir.

Explain what each tool does (a line or two would probably enough for each tool), whether there are gotchas to be aware of, etc.

For instance, I _think_ mpv-install.bat only does file associations, but users could think that it installs mpv to some place, and that they can delete the extracted dir after installation. Or maybe it does some other things other than file associations, etc - it's hard to tell because the script is not small, and not all users can read and understand scripts.

The other tools would also benefit from a short description.

Thanks.

**Comment by shinchiro** [comment]
Everything is pretty self explained when running cmd so there's no need for it.
https://github.com/shinchiro/mpv-packaging/blob/9528bc612914a5b683a1812127302d8e34b4160a/mpv-root/installer/mpv-install.bat#L293

**Comment by avih** [comment]
> Everything is pretty self explained when running cmd

That could be a bit late if you want to avoid certain system changes, but you can't know which changes it will make without running it...
