### ISSUE TITLE
Cannot index into a null array.

### ISSUE THREAD

**Issue by Obegg** [shinchiro/mpv-packaging#22]
![Untitled](https://user-images.githubusercontent.com/13978119/159196960-17c8ff11-979c-476f-832f-ee169faa65b3.png)

**Comment by Obegg** [comment]
I believe it's because GitHub actions didn't upload a new .zip file.
https://github.com/shinchiro/mpv-winbuild-cmake/releases/tag/20220321
So there is nothing to download.

**Comment by shinchiro** [comment]
Should be fix by now

**Comment by Obegg** [comment]
@shinchiro Issue was fixed but today it's not fixed.
Updater shows the same screen.
![image](https://user-images.githubusercontent.com/13978119/161472395-9e68157d-125c-4821-a53b-8065e1d5e7c7.png)
