### ISSUE TITLE
Auto-Update FFmpeg

### ISSUE THREAD

**Issue by Obegg** [shinchiro/mpv-packaging#24]
The latest commit https://github.com/shinchiro/mpv-winbuild-cmake/commit/1e2c139b18591ead8713ff100aac4028df1076c7 adds `FFmpeg` to https://github.com/shinchiro/mpv-winbuild-cmake/releases

Will it be possible to add `FFmpeg` as Auto-Update the same way it's updating `mpv` and `yt-dlp`?
(Here: https://github.com/shinchiro/mpv-packaging/blob/master/mpv-root/installer/updater.ps1)

Also - Since `FFmpeg` is named `ffmpeg_x64.exe`, I would love to have to option that it will auto-rename it to `ffmpeg.exe` since Windows, or other applications that use `FFmpeg` won't be able to find it unless it's named `ffmpeg.exe`

**Comment by shinchiro** [comment]
old `settings.xml` file should be deleted to let new updater generate new xml with ffmpeg support
