### ISSUE TITLE
Updater.ps1 script is creating empty channel element in settings.xml file 

### ISSUE THREAD

**Issue by wladitavar** [shinchiro/mpv-packaging#25]
Hi!

Updater.ps1 script is creating empty channel element in settings.xml file when the timer runs out or if the user choses a value different from D1 or D2 and it is causing the `Cannot index into a null array.` error when the timer runs out.

`function Check-ChannelRelease` is suggesting on the output that the user should choose daily or weekly updates frequency and then it's checking users input as D1 for weekly and D2 for daily and it's also accepting any other value the user types.

My suggestion is to force either daily or week update channel as the default update channel.

By replacing the test on the line 223

`
        elseif ($result -eq 'D2') {
`

with 

`
        else {
`

we would be forcing daily update channel.

Lastly, I understand that by forcing the default update channel to daily may increase the number of requests on the server. But then you ought to change the default channel to weekly.

**Comment by shinchiro** [comment]
fyi, `Cannot index into a null array` error is not caused by timer runs out
