### ISSUE TITLE
A few suggestions

### ISSUE THREAD

**Issue by Smithy3** [shinchiro/mpv-packaging#3]
- The updater script should also delete the downloaded .7z file.
- Installer should create a start menu link to the mpv executable so it functions like a normal install. I've tried doing thing myself, but it would probably have to rely on PowerShell to create an actual shortcut file, as in an `.lnk` file.
- This is probably beyond the scope of the `install.bat` script, but it would be nice if there was a registry entry for mpv under `HKLM\Software\Microsoft\Windows\CurrentVersion\Uninstall` so the installer functions like an actual installer, with an `UninstallString` referencing the `uninstall.bat` file.

On a side note, I really appreciate your mpv builds and I thank you for making them.

**Comment by Smithy3** [comment]
I apologize if this came across as demanding, it was never my intention.

**Comment by shinchiro** [comment]
The 7z archive is not deleted automatically to give users option to revert back to old version. Point 2 also good suggestion. But I'm just lazy

**Comment by Smithy3** [comment]
Ah, that would make sense for the first point.
I've created a pull request for the second point (see https://github.com/shinchiro/mpv-packaging/pull/6).
I'll look into the 3rd point at some point in the future.

**Comment by Smithy3** [comment]
I've put together a working script that creates a folder in the start menu with shortcuts to the documentation, keybindings, updater, uninstaller (with "run as admin" enabled), and the mpv executable.

I can either submit a PR to the mpv-install.bat and mpv-uninstall.bat or just release it as a standalone PowerShell script. Which would make more sense? I ask as it depends on PowerShell and while it does fully work inside the existing Batch script, I can understand why it might not be the best idea.

Ignore PR #6, that was just for the executable until I expanded it and I've now closed it.

**Comment by Smithy3** [comment]
With regards to the first point, it could very easily be made optional with a Y/N prompt.

I don't know what you mean by "using it as portable". If you are running the `mpv-install.bat` file, then it isn't portable. The whole idea behind portable software is that [it does not make any alterations to the users computer](https://en.wikipedia.org/wiki/List_of_portable_software), which that script clearly does.

The reason I suggested it in the first place is that all installers create start links. The only time I found software that didn't was some obscure and not very good audio file tagging program. Wouldn't it make more sense for an installer to work like all other installers?

Also, a desktop shortcut is not the same as an entry in the start menu. That won't make it show up under the list of applications in the start menu. Its a different thing altogether.

**Comment by dnmTX** [comment]
Do what you like man,don't really feel like arguing with another **smarty**.Plenty of  those here.

**Comment by Smithy3** [comment]
I see you're still bitter from https://github.com/mpv-player/mpv/issues/5932.
I recognized you from then and still gave you a proper response, yet you couldn't do the same.
Grow up.

**Comment by dnmTX** [comment]
Ohhh....if i knew it was you i never would've posted here.Just disregard everything i wrote and go be **SMART**.I'm done here.

**Comment by Smithy3** [comment]
As I said, grow up.

**Comment by Smithy3** [comment]
While the folder did work I didn't really like it, so I've changed it back to just a simple .exe start menu link.
PR https://github.com/shinchiro/mpv-packaging/pull/7.

**Comment by shinchiro** [comment]
Can be closed now
