### ISSUE TITLE
mpv-install.bat: add mpv to `%PATH%`

### ISSUE THREAD

**Issue by Obegg** [shinchiro/mpv-packaging#43]
Current behavior:
Open `cmd` and type `mpv`:
```
'mpv' is not recognized as an internal or external command,
operable program or batch file.
```

Suggested behavior:
add mpv to `%PATH%` so that if I type `mpv` in `cmd` it will open mpv.

**Comment by xd003** [comment]
You can always add a directory to path say .local\bin
```
[Environment]::SetEnvironmentVariable("Path", $env:Path + ";$env:USERPROFILE\.local\bin", "User")
```

Then symlink mpv.exe to that directory, change the target based on location of your mpv.exe
```
New-Item -ItemType SymbolicLink -Path "$env:USERPROFILE\.local\bin\mpv.exe" -Target "$env:ProgramFiles\mpv\mpv.exe" -Force
```

**Comment by shinchiro** [comment]
Adding to $PATH will create issue for someone who has multiple mpv.exe in their system, which I not adding it by default
